# Generated by Django 5.0.4 on 2024-04-29 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_surveys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveys',
            name='survey',
            field=models.JSONField(),
        ),
    ]
