# Generated by Django 5.0.4 on 2024-05-01 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_surveys_survey'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveys',
            name='access_hash',
            field=models.UUIDField(default=None, unique=True),
        ),
        migrations.AddField(
            model_name='surveys',
            name='uuid',
            field=models.UUIDField(default=None, unique=True),
        ),
    ]
